### PR TITLE
Changable hasher

### PR DESCRIPTION
**Pull request by fmkra**
- Merge blake2s and keccak versions into one branch
- Add bash scripts for changing between versions

To change version run either `blake.sh` or `keccak.sh`. By default keccak is active.

### CODE REVIEW

**Comment by Okm165** [comment]
@fmkra pls check if os selection scripts work for u

**Comment by fmkra** [comment]
> @fmkra pls check if os selection scripts work for u

Works great

**Comment by Okm165** [comment]
One minor issue persists when using `keccak.sh` with the native Keccak implementation: it repeatedly adds comment symbols indefinitely to the parts related to Blake2s, and vice versa.

**Review by Okm165 — APPROVED** [review]
LGTM!!!

**Pull request merged**
