### PR TITLE
eval_oods_polynomial impl

### PR DESCRIPTION
**Pull request by Okm165**

### CODE REVIEW

**Review by tiagofneto — COMMENTED** [review]
This function is not expected to be directly called in `stark_decommit` correct?

I believe there is still another function on top that prepares some arguments for this one: https://github.com/starkware-libs/cairo-lang/blob/9e6e0e96d208608d98635ccfad5b26285c4936e1/src/starkware/cairo/stark_verifier/air/oods.cairo#L20

**Comment by Okm165** [comment]
Yes there is :)
I left because i will develop it in stark-verify branch
It is not part of this issue

**Comment by Okm165** [comment]
or maybe i should separate it as other issue rather, so not to large prs there

**Comment by tiagofneto** [comment]
I think it would be good to have it here but up to you @Okm165

**Comment by Okm165** [comment]
ok let's go with it
pls review additional function @tiagofneto

**Review by tiagofneto — APPROVED** [review]

**Pull request merged**
